pretrained_model_path: ./checkpoints/stable-diffusion-v1-4
output_dir: ./outputs/drift-turn
train_data:
  video_path: ./data/drift-turn.mp4
  prompt: A car drifts on a racetrack.
  height: 480
  width: 480
  n_sample_frames: 16
  sample_start_idx: 0
  sample_frame_rate: 2
validation_data:
  prompts:
    - A car drifts on a racetrack, neon lights.
  video_length: 16
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 100
checkpointing_steps: 1000
validation_steps: 100
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
